# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardDisplay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardDisplay
  pod 'AZTabBar'
  pod 'SDWebImage'

  target 'CardDisplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardDisplayUITests' do
    # Pods for testing
  end

end
